[workspace]
authors = ["Nhi Nguyen <nhi.nguyen8464@gmail.com>"]
channels = ["conda-forge"]
name = "BINF-5507-Materials"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
pip = ">=25.1.1,<26"
matplotlib = ">=3.10.3,<4"
scikit-learn = ">=1.6.1,<2"
seaborn = ">=0.13.2,<0.14"
pandas = ">=2.2.3,<3"
